controller:
  replicaCount: 2
  nodeSelector:
    kubernetes.io/os: linux
  admissionWebhooks:
    patch:
      nodeSelector:
        kubernetes.io/os: linux
  service:
    loadBalancerIP: # > "IP address from the terraform output" <
    externalTrafficPolicy: Local
defaultBackend:
  nodeSelector:
    kubernetes.io/os: linux
