apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-1
  template:
    metadata:
      labels:
        app: webapp-1
    spec:
      containers:
        - name: webapp-1
          image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              valueFrom:
                configMapKeyRef:
                  name: webapps-cm
                  key: TITLE_webapp_1
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-1-srv
spec:
  selector:
    app: webapp-1
  type: ClusterIP
  ports:
    - port: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
